{"trial_id": "0020", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh"], "ordered": false}}, {"class_name": "Int", "config": {"name": "layer_1", "default": null, "conditions": [], "min_value": 1, "max_value": 1000, "step": 100, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "layer_2", "default": null, "conditions": [], "min_value": 1, "max_value": 1000, "step": 100, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}], "values": {"activation": "relu", "layer_1": 701, "layer_2": 901, "learning_rate": 0.001, "tuner/epochs": 10, "tuner/initial_epoch": 4, "tuner/bracket": 1, "tuner/round": 1, "tuner/trial_id": "0016"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 60, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node div_no_nan_1 defined at (most recent call last):\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/traitlets/config/application.py\", line 1041, in launch_instance\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 724, in start\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 215, in start\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/asyncio/base_events.py\", line 1906, in _run_once\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 512, in dispatch_queue\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 501, in process_one\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 408, in dispatch_shell\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 731, in execute_request\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 417, in do_execute\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2945, in run_cell\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3000, in _run_cell\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3203, in run_cell_async\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3382, in run_ast_nodes\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3442, in run_code\n\n  File \"/var/folders/d4/chxwf4hs5kq7ttsp56s64z65mjk3qj/T/ipykernel_23758/3329127275.py\", line 38, in <module>\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 233, in search\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1783, in fit\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1377, in train_function\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1360, in step_function\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1349, in run_step\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1131, in train_step\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1226, in compute_metrics\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1242, in get_metrics_result\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/utils/metrics_utils.py\", line 138, in decorated\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/metrics/base_metric.py\", line 159, in result_fn\n\n  File \"/Users/rem76/miniconda3/envs/GISP_init/lib/python3.10/site-packages/keras/src/metrics/confusion_metrics.py\", line 1603, in result\n\nIncompatible shapes: [200] vs. [0]\n\t [[{{node div_no_nan_1}}]] [Op:__inference_train_function_496507]\n"}